using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Damdor.Statio.CodeGenerator;

/// <summary>
/// Provides source generation of Unity initialization methods that register attributed classes.
/// </summary>
public abstract class ClassRegisterViaAttributeCodeGenerator : ISourceGenerator
{
    /// <summary>
    /// Gets the attribute names to collect, without the Attribute suffix.
    /// </summary>
    public abstract string[] Attributes { get; } 
    
    /// <summary>
    /// Registers the attribute syntax receiver.
    /// </summary>
    /// <param name="context">The Roslyn initialization context.</param>
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new AttributeSyntaxReceiver(Attributes));
    }

    /// <summary>
    /// Generates registration source for the current compilation.
    /// </summary>
    /// <param name="context">The Roslyn generation context.</param>
    public abstract void Execute(GeneratorExecutionContext context);
    
    /// <summary>
    /// Generates registration calls for concrete classes whose attributes pass semantic validation.
    /// </summary>
    /// <param name="context">The Roslyn generation context.</param>
    /// <param name="attribute">The collected attribute name without the Attribute suffix.</param>
    /// <param name="register">The callback that appends a registration statement for each fully qualified type name.</param>
    protected void GenerateForAttribute(
            GeneratorExecutionContext context, 
            string attribute, 
            Action<StringBuilder, string> register)
        {
            if (context.SyntaxReceiver is not AttributeSyntaxReceiver receiver) return;
            
             var typesToRegister = new List<string>();

            foreach (var classDecl in receiver.CandidateClasses[attribute])
            {
                var semanticModel = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol) continue;
                if (classSymbol.IsAbstract || classSymbol.TypeKind == TypeKind.Interface) continue;

                var hasAttribute = classSymbol.GetAttributes().Any(ad =>
                    ad.AttributeClass?.Name == attribute + "Attribute" ||
                    ad.AttributeClass?.Name == attribute);

                if (hasAttribute)
                {
                    typesToRegister.Add(classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }
            }

            if (typesToRegister.Count == 0) return;

            var assemblyName = context.Compilation.AssemblyName?.Replace(".", "_").Replace("-", "_");
            var generatedClassName = $"{attribute}Registration_{assemblyName}";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine();
            sb.AppendLine($"internal static class {generatedClassName}");
            sb.AppendLine("{");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("    [UnityEditor.InitializeOnLoadMethod]");
            sb.AppendLine("#endif");            
            sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]");
            sb.AppendLine("    private static void Register()");
            sb.AppendLine("    {");

            foreach (var type in typesToRegister) register(sb, type);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{generatedClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    
}